# -*- coding: utf-8 -*-
"""Data_Structures_&_Built_in_Fns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QF2UvwJd8p9NcVvjYp3-g4f7T1TMhe3v

Task 1 — Tuples Create a tuple of five city names, unpack it into five separate variables, and print each variable. Then try to modify the first element and handle the resulting error with a try-except block that prints a clear message.
"""

cities = ("London", "Paris", "Tokyo", "New York", "Rome")
city1, city2, city3, city4, city5 = cities

print(f"City 1: {city1}")
print(f"City 2: {city2}")
print(f"City 3: {city3}")
print(f"City 4: {city4}")
print(f"City 5: {city5}")

try:
    cities[0] = "Berlin"
except TypeError as e:
    print(f"Error: Tuples are immutable and cannot be modified. Details: {e}")

"""Task 2 — Sets Create two sets — one for students who passed a Python test and one for students who passed a SQL test. Print the union, intersection, and difference (Python-only passers) using set operators."""

python_passed_students = {"Akanksha", "Babby", "Chandu", "Danush", "Eshan"}
sql_passed_students = {"Chandu", "Danush", "Jessy", "Greeshma", "Hari"}

# Union of students who passed either Python or SQL
all_passed = python_passed_students | (sql_passed_students)
print(f"All students who passed at least one test: {all_passed}")

# Intersection of students who passed both Python and SQL
both_passed = python_passed_students & (sql_passed_students)
print(f"Students who passed both tests: {both_passed}")

# Difference (students who passed Python but not SQL)
python_only_passed = python_passed_students - (sql_passed_students)
print(f"Students who passed Python only: {python_only_passed}")

"""Task 3 — Lists and ASCII Create a list of five integers representing ASCII values. Use a loop with chr() to print each integer alongside its corresponding character. Then use ord() to retrieve and print the ASCII value of the character 'Z'."""

# Create a list of five integers representing ASCII values
ascii_values = [65, 101, 73, 48, 117] # A, e, I, 0, u

print("ASCII values and their corresponding characters:")
# Use a loop with chr() to print each integer alongside its corresponding character
for value in ascii_values:
    print(f"ASCII value: {value}, Character: {chr(value)}")

# Use ord() to retrieve and print the ASCII value of the character 'Z'
char_z_ascii = ord('Z')
print(f"\nThe ASCII value of 'Z' is: {char_z_ascii}")

"""Task 4 — Subprocess Use the subprocess module to run the shell command whoami and print the captured output using result.stdout."""

import subprocess

# Run the 'whoami' shell command
result = subprocess.run(['whoami'], capture_output=True, text=True)

# Print the captured output
print(f"Current user: {result.stdout.strip()}")

