# -*- coding: utf-8 -*-
"""Json_in_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hroZWqC3NQ5Wbz8W0nuF8D4bYF1s_BX3

Task 1 — Create and Serialise a Nested JSON Object Create a Python dictionary representing a student with keys: name, age, passed (boolean), marks (list of three numbers), and a nested address object containing city and pincode. Convert it to a formatted JSON string using json.dumps() with indent=4 and print the result.
"""

import json

# Task 1 — Create and Serialise a Nested JSON Object
print("--- Task 1 ---")
student_data = {
    "name": "Alice",
    "age": 20,
    "passed": True,
    "marks": [85, 92, 78],
    "address": {
        "city": "New York",
        "pincode": "10001"
    }
}
formatted_json_string = json.dumps(student_data, indent=4)
print("Formatted JSON string:")
print(formatted_json_string)

"""Task 2 — Parse JSON and Access Values Using json.loads(), parse the JSON string from Task 1 back into a Python dictionary. Print the student's name, the second marks value, and the city from the nested address.


"""

import json
# Task 2 — Parse JSON and Access Values
print("\n--- Task 2 ---")
parsed_student = json.loads(formatted_json_string)
print(f"Student Name: {parsed_student['name']}")
print(f"Second Marks Value: {parsed_student['marks'][1]}")
print(f"City: {parsed_student['address']['city']}")

"""Task 3 — Identify and Fix Invalid JSON The following JSON string contains two syntax errors. Identify them in a comment, fix the string, parse it using json.loads(), and print the result.\n\npython\nbad_json = '{ name: \"Raj\", \"score\": 88, \"active\": true, }'\n


"""

import json
# Task 3 — Identify and Fix Invalid JSON
print("\n--- Task 3 ---")
bad_json = '{ name: "Raj", "score": 88, "active": true, }'
print(f"Original bad JSON: {bad_json}")

# Fixes:
# 1. Key 'name' is not double-quoted. JSON keys must be strings enclosed in double quotes.
# 2. There is a trailing comma after 'true,'. JSON objects do not allow trailing commas.
fixed_json = '{ "name": "Raj", "score": 88, "active": true }'
print(f"Fixed JSON: {fixed_json}")
try:
    parsed_bad_json = json.loads(fixed_json)
    print("Parsed fixed JSON successfully:")
    print(parsed_bad_json)
except json.JSONDecodeError as e:
    print(f"Error parsing fixed JSON: {e}")

"""Task 4 — Build a JSON Array of Objects Create a Python list of three dictionaries, each representing a product with keys product_name, price, and in_stock (boolean). Convert the list to a JSON string with indent=2 and print it."""

import json
# Task 4 — Build a JSON Array of Objects
print("\n--- Task 4 ---")
products = [
    {
        "product_name": "Laptop",
        "price": 1200.50,
        "in_stock": True
    },
    {
        "product_name": "Mouse",
        "price": 25.00,
        "in_stock": True
    },
    {
        "product_name": "Keyboard",
        "price": 75.99,
        "in_stock": False
    }
]
products_json_string = json.dumps(products, indent=2)
print("JSON array of products:")
print(products_json_string)